opcode_table = {
    'rep': [None, None, None, 0xC2, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'lda': [None, 0xA9, None, None, None, None, 0xA5, 0xB5, None, 0xB2, 0xA1, 0xB1, 0xA7, 0xB7, 0xAD, 0xBD, 0xB9, 0xAF, 0xBF, 0xA3, 0xB3, None, None, None, None, None],
    'ldx': [None, None, 0xA2, None, None, None, 0xA6, None, 0xB6, None, None, None, None, None, 0xAE, None, 0xBE, None, None, None, None, None, None, None, None, None],
    'ldy': [None, None, 0xA0, None, None, None, 0xA4, 0xB4, None, None, None, None, None, None, 0xAC, 0xBC, None, None, None, None, None, None, None, None, None, None],
#
    'cmp': [None, 0xC9, None, None, None, None, 0xC5, 0xD5, None, 0xD3, 0xC1, 0xD1, 0xC7, 0xD7, 0xCD, 0xDD, 0xD9, 0xCF, 0xDF, 0xC3, None, None, None, None, None, None],
    'cpy': [None, None, 0xC0, None, None, None, 0xC4, None, None, None, None, None, None, None, 0xCC, None, None, None, None, None, None, None, None, None, None, None],
    'cpx': [None, None, 0xE0, None, None, None, 0xE4, None, None, None, None, None, None, None, 0xEC, None, None, None, None, None, None, None, None, None, None, None],
#
    'sta': [None, None, None, None, None, None, 0x85, 0x95, None, 0x92, 0x81, 0x91, 0x87, 0x97, 0x8D, 0x9D, 0x99, 0x8F, 0x9F, 0x83, 0x93, None, None, None, None, None],
    'stx': [None, None, None, None, None, None, 0x86, None, 0x96, None, None, None, None, None, 0x8E, None, None, None, None, None, None, None, None, None, None, None],
    'sty': [None, None, None, None, None, None, 0x84, 0x94, None, None, None, None, None, None, 0x8C, None, None, None, None, None, None, None, None, None, None, None],
    'stz': [None, None, None, None, None, None, 0x64, 0x74, None, None, None, None, None, None, 0x9C, 0x9E, None, None, None, None, None, None, None, None, None, None],
    #
    'bcc': [None, None, None, None, 0x90, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'bcs': [None, None, None, None, 0xB0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'bpl': [],
    'bmi': [None, None, None, None, 0x30, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'bne': [None, None, None, None, 0xD0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'beq': [None, None, None, None, 0xF0, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'bvc': [None, None, None, None, 0x10, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'bvs': [None, None, None, None, 0x70, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'brl': [None, None, None, None, None, 0x82, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'bra': [None, None, None, None, 0x80, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    #
    'adc': [None, 0x69, None, None, None, None, 0x65, 0x75, None, 0x72, 0x61, 0x71, 0x67, 0x77, 0x6D, 0x7D, 0x79, 0x6F, 0x7F, 0x63, 0x73, None, None, None, None, None],
    'sbc': [None, 0xE9, None, None, None, None, 0xE5, 0xF5, None, 0xF2, 0xE1, 0xF1, 0xE7, 0xF7, 0xED, 0xFD, 0xF9, 0xEF, 0xFF, 0xE3, 0xF3, None, None, None, None, None],
    'inc': [0x1A, None, None, None, None, None, 0xE6, 0xF6, None, None, None, None, None, None, 0xEE, 0xFE, None, None, None, None, None, None, None, None, None, None],
    'inx': [0xE8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'iny': [0xC8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'dec': [0x3A, None, None, None, None, None, 0xC6, 0xD6, None, None, None, None, None, None, 0xCE, 0xDE, None, None, None, None, None, None, None, None, None, None],
    'dex': [0xCA, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'dey': [0x88, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    #
    'pea': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0xF4, None, None, None, None, None, None, None, None, None, None, 0xF4],
    'pei': [None, None, None, None, None, None, 0xD4, None, None, 0xD4, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'per': [None, None, None, None, None, 0x62, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'pha': [0x48, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'phb': [0x8B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'phd': [0x0B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'phk': [0x4B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'php': [0x08, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'phx': [0xDA, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'phy': [0x5A, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'pla': [0x68, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'plb': [0xAB, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'pld': [0x2B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'plp': [0x28, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'plx': [0xFA, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'ply': [0x7A, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    #
    'and': [None, 0x29, None, None, None, None, 0x25, 0x35, None, 0x32, 0x21, 0x31, 0x27, 0x37, 0x2D, 0x3D, 0x39, 0x2F, 0x3F, 0x23, 0x33, None, None, None, None, None],
    'asl': [0x0A, None, None, None, None, None, 0x06, 0x16, None, None, None, None, None, None, 0x0E, 0x1E, None, None, None, None, None, None, None, None, None, None],
    'bit': [None, 0x89, None, None, None, None, 0x24, 0x34, None, None, None, None, None, None, 0x2C, 0x3C, None, None, None, None, None, None, None, None, None, None],
    'eor': [None, 0x49, None, None, None, None, 0x45, 0x55, None, 0x52, 0x41, 0x51, 0x47, 0x57, 0x4D, 0x5D, 0x59, 0x4F, 0x5F, 0x43, 0x53, None, None, None, None, None],
    'lsr': [0x4A, None, None, None, None, None, 0x46, 0x56, None, None, None, None, None, None, 0x4E, 0x5E, None, None, None, None, None, None, None, None, None, None],
    'ora': [None, 0x09, None, None, None, None, 0x05, 0x15, None, 0x12, 0x01, 0x11, 0x07, 0x17, 0x0D, 0x1D, 0x19, 0x0F, 0x1F, 0x03, 0x13, None, None, None, None, None],
    'rol': [0x2A, None, None, None, None, None, 0x26, 0x36, None, None, None, None, None, None, 0x2E, 0x3E, None, None, None, None, None, None, None, None, None, None],
    'ror': [0x6A, None, None, None, None, None, 0x66, 0x76, None, None, None, None, None, None, 0x6E, 0x7E, None, None, None, None, None, None, None, None, None, None],
    'trb': [None, None, None, None, None, None, 0x14, None, None, None, None, None, None, None, 0x1C, None, None, None, None, None, None, None, None, None, None, None],
    'tsb': [None, None, None, None, None, None, 0x04, None, None, None, None, None, None, None, 0x0C, None, None, None, None, None, None, None, None, None, None, None],
    #
    'tax': [0xAA, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'tay': [0xA8, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'tcd': [0x5B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'tcs': [0x1B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'tdc': [0x7B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'tsc': [0x3B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'tsx': [0xBA, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'txa': [0x8A, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'txs': [0x9A, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'txy': [0x9B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'tya': [0x98, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'tyx': [0xBB, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'mvn': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0x54, None, None, None, None, None, None, None, None, None, 0x54, None],
    'mvp': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0x44, None, None, None, None, None, None, None, None, None, 0x44, None],
    #
    'jml': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0xDC, None, None, None],
    'jsp': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0x4C, None, None, 0x5C, None, None, None, 0x6C, None, 0x7C, None, None],
    'jsl': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0x22, None, None, None, None, None, None, None, None],
    'jsr': [None, None, None, None, None, None, None, None, None, None, None, None, None, None, 0x20, None, None, None, None, None, None, None, None, 0xFC, None, None],
    'rti': [0x40, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'rtl': [0x6B, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'rts': [0x60, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    #
    'brk': [None, None, None, 0x00, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'cop': [None, None, None, 0x02, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'nop': [0xEA, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'stp': [0xDB, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'wai': [0xCB, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'xba': [0xEB, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None],
    'xce': [0xFB, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None, None]
}
