  on:
    push:
  jobs:
    binaries:
      runs-on: windows-latest
      steps:
        - uses: actions/checkout@v3
        - name: Setup Python 3.10
          uses: actions/setup-python@v4
          with:
            python-version: '3.10'
        - name: Install hatch
          run: pip install hatch
        - name: Build binary
          run: make binary
        - uses: actions/upload-artifact@v2
          with:
            name: binaries
            path: build/*
