on:
  push:
    tags-ignore:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install hatch
      run: pip install hatch
    - name: Type check
      run: hatch run tests:type
    - name: Style check
      run: hatch run tests:check
    - name: Run tests
      run: hatch run tests:coverage
    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        GH_TOKEN: ${{ github.token }}

